/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PryvatnistRouteImport } from './routes/pryvatnist'
import { Route as ProKompaniyuRouteImport } from './routes/pro-kompaniyu'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoslugyIndexRouteImport } from './routes/poslugy.index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as PoslugyZagalnobudivelniRobotyRouteImport } from './routes/poslugy.zagalnobudivelni-roboty'
import { Route as PoslugySteliRouteImport } from './routes/poslugy.steli'
import { Route as PoslugySantehnikaElektrykaRouteImport } from './routes/poslugy.santehnika-elektryka'
import { Route as PoslugyRemontPidKlyuchRouteImport } from './routes/poslugy.remont-pid-klyuch'
import { Route as PoslugyOzdoblennyaRouteImport } from './routes/poslugy.ozdoblennya'
import { Route as PoslugyGipsokartonRouteImport } from './routes/poslugy.gipsokarton'
import { Route as PoslugyDemontazhRouteImport } from './routes/poslugy.demontazh'
import { Route as EnPryvatnistRouteImport } from './routes/en.pryvatnist'
import { Route as EnProKompaniyuRouteImport } from './routes/en.pro-kompaniyu'
import { Route as EnPortfolioRouteImport } from './routes/en.portfolio'
import { Route as EnKontaktyRouteImport } from './routes/en.kontakty'
import { Route as EnPoslugyIndexRouteImport } from './routes/en.poslugy.index'
import { Route as EnPoslugyZagalnobudivelniRobotyRouteImport } from './routes/en.poslugy.zagalnobudivelni-roboty'
import { Route as EnPoslugySteliRouteImport } from './routes/en.poslugy.steli'
import { Route as EnPoslugySantehnikaElektrykaRouteImport } from './routes/en.poslugy.santehnika-elektryka'
import { Route as EnPoslugyRemontPidKlyuchRouteImport } from './routes/en.poslugy.remont-pid-klyuch'
import { Route as EnPoslugyOzdoblennyaRouteImport } from './routes/en.poslugy.ozdoblennya'
import { Route as EnPoslugyGipsokartonRouteImport } from './routes/en.poslugy.gipsokarton'
import { Route as EnPoslugyDemontazhRouteImport } from './routes/en.poslugy.demontazh'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PryvatnistRoute = PryvatnistRouteImport.update({
  id: '/pryvatnist',
  path: '/pryvatnist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProKompaniyuRoute = ProKompaniyuRouteImport.update({
  id: '/pro-kompaniyu',
  path: '/pro-kompaniyu',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugyIndexRoute = PoslugyIndexRouteImport.update({
  id: '/poslugy/',
  path: '/poslugy/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugyZagalnobudivelniRobotyRoute =
  PoslugyZagalnobudivelniRobotyRouteImport.update({
    id: '/poslugy/zagalnobudivelni-roboty',
    path: '/poslugy/zagalnobudivelni-roboty',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoslugySteliRoute = PoslugySteliRouteImport.update({
  id: '/poslugy/steli',
  path: '/poslugy/steli',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugySantehnikaElektrykaRoute =
  PoslugySantehnikaElektrykaRouteImport.update({
    id: '/poslugy/santehnika-elektryka',
    path: '/poslugy/santehnika-elektryka',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoslugyRemontPidKlyuchRoute = PoslugyRemontPidKlyuchRouteImport.update({
  id: '/poslugy/remont-pid-klyuch',
  path: '/poslugy/remont-pid-klyuch',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugyOzdoblennyaRoute = PoslugyOzdoblennyaRouteImport.update({
  id: '/poslugy/ozdoblennya',
  path: '/poslugy/ozdoblennya',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugyGipsokartonRoute = PoslugyGipsokartonRouteImport.update({
  id: '/poslugy/gipsokarton',
  path: '/poslugy/gipsokarton',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslugyDemontazhRoute = PoslugyDemontazhRouteImport.update({
  id: '/poslugy/demontazh',
  path: '/poslugy/demontazh',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPryvatnistRoute = EnPryvatnistRouteImport.update({
  id: '/en/pryvatnist',
  path: '/en/pryvatnist',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProKompaniyuRoute = EnProKompaniyuRouteImport.update({
  id: '/en/pro-kompaniyu',
  path: '/en/pro-kompaniyu',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPortfolioRoute = EnPortfolioRouteImport.update({
  id: '/en/portfolio',
  path: '/en/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKontaktyRoute = EnKontaktyRouteImport.update({
  id: '/en/kontakty',
  path: '/en/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPoslugyIndexRoute = EnPoslugyIndexRouteImport.update({
  id: '/en/poslugy/',
  path: '/en/poslugy/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPoslugyZagalnobudivelniRobotyRoute =
  EnPoslugyZagalnobudivelniRobotyRouteImport.update({
    id: '/en/poslugy/zagalnobudivelni-roboty',
    path: '/en/poslugy/zagalnobudivelni-roboty',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnPoslugySteliRoute = EnPoslugySteliRouteImport.update({
  id: '/en/poslugy/steli',
  path: '/en/poslugy/steli',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPoslugySantehnikaElektrykaRoute =
  EnPoslugySantehnikaElektrykaRouteImport.update({
    id: '/en/poslugy/santehnika-elektryka',
    path: '/en/poslugy/santehnika-elektryka',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnPoslugyRemontPidKlyuchRoute =
  EnPoslugyRemontPidKlyuchRouteImport.update({
    id: '/en/poslugy/remont-pid-klyuch',
    path: '/en/poslugy/remont-pid-klyuch',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnPoslugyOzdoblennyaRoute = EnPoslugyOzdoblennyaRouteImport.update({
  id: '/en/poslugy/ozdoblennya',
  path: '/en/poslugy/ozdoblennya',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPoslugyGipsokartonRoute = EnPoslugyGipsokartonRouteImport.update({
  id: '/en/poslugy/gipsokarton',
  path: '/en/poslugy/gipsokarton',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPoslugyDemontazhRoute = EnPoslugyDemontazhRouteImport.update({
  id: '/en/poslugy/demontazh',
  path: '/en/poslugy/demontazh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/pro-kompaniyu': typeof ProKompaniyuRoute
  '/pryvatnist': typeof PryvatnistRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/kontakty': typeof EnKontaktyRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/pro-kompaniyu': typeof EnProKompaniyuRoute
  '/en/pryvatnist': typeof EnPryvatnistRoute
  '/poslugy/demontazh': typeof PoslugyDemontazhRoute
  '/poslugy/gipsokarton': typeof PoslugyGipsokartonRoute
  '/poslugy/ozdoblennya': typeof PoslugyOzdoblennyaRoute
  '/poslugy/remont-pid-klyuch': typeof PoslugyRemontPidKlyuchRoute
  '/poslugy/santehnika-elektryka': typeof PoslugySantehnikaElektrykaRoute
  '/poslugy/steli': typeof PoslugySteliRoute
  '/poslugy/zagalnobudivelni-roboty': typeof PoslugyZagalnobudivelniRobotyRoute
  '/en/': typeof EnIndexRoute
  '/poslugy/': typeof PoslugyIndexRoute
  '/en/poslugy/demontazh': typeof EnPoslugyDemontazhRoute
  '/en/poslugy/gipsokarton': typeof EnPoslugyGipsokartonRoute
  '/en/poslugy/ozdoblennya': typeof EnPoslugyOzdoblennyaRoute
  '/en/poslugy/remont-pid-klyuch': typeof EnPoslugyRemontPidKlyuchRoute
  '/en/poslugy/santehnika-elektryka': typeof EnPoslugySantehnikaElektrykaRoute
  '/en/poslugy/steli': typeof EnPoslugySteliRoute
  '/en/poslugy/zagalnobudivelni-roboty': typeof EnPoslugyZagalnobudivelniRobotyRoute
  '/en/poslugy/': typeof EnPoslugyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/pro-kompaniyu': typeof ProKompaniyuRoute
  '/pryvatnist': typeof PryvatnistRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/kontakty': typeof EnKontaktyRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/pro-kompaniyu': typeof EnProKompaniyuRoute
  '/en/pryvatnist': typeof EnPryvatnistRoute
  '/poslugy/demontazh': typeof PoslugyDemontazhRoute
  '/poslugy/gipsokarton': typeof PoslugyGipsokartonRoute
  '/poslugy/ozdoblennya': typeof PoslugyOzdoblennyaRoute
  '/poslugy/remont-pid-klyuch': typeof PoslugyRemontPidKlyuchRoute
  '/poslugy/santehnika-elektryka': typeof PoslugySantehnikaElektrykaRoute
  '/poslugy/steli': typeof PoslugySteliRoute
  '/poslugy/zagalnobudivelni-roboty': typeof PoslugyZagalnobudivelniRobotyRoute
  '/en': typeof EnIndexRoute
  '/poslugy': typeof PoslugyIndexRoute
  '/en/poslugy/demontazh': typeof EnPoslugyDemontazhRoute
  '/en/poslugy/gipsokarton': typeof EnPoslugyGipsokartonRoute
  '/en/poslugy/ozdoblennya': typeof EnPoslugyOzdoblennyaRoute
  '/en/poslugy/remont-pid-klyuch': typeof EnPoslugyRemontPidKlyuchRoute
  '/en/poslugy/santehnika-elektryka': typeof EnPoslugySantehnikaElektrykaRoute
  '/en/poslugy/steli': typeof EnPoslugySteliRoute
  '/en/poslugy/zagalnobudivelni-roboty': typeof EnPoslugyZagalnobudivelniRobotyRoute
  '/en/poslugy': typeof EnPoslugyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakty': typeof KontaktyRoute
  '/portfolio': typeof PortfolioRoute
  '/pro-kompaniyu': typeof ProKompaniyuRoute
  '/pryvatnist': typeof PryvatnistRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/kontakty': typeof EnKontaktyRoute
  '/en/portfolio': typeof EnPortfolioRoute
  '/en/pro-kompaniyu': typeof EnProKompaniyuRoute
  '/en/pryvatnist': typeof EnPryvatnistRoute
  '/poslugy/demontazh': typeof PoslugyDemontazhRoute
  '/poslugy/gipsokarton': typeof PoslugyGipsokartonRoute
  '/poslugy/ozdoblennya': typeof PoslugyOzdoblennyaRoute
  '/poslugy/remont-pid-klyuch': typeof PoslugyRemontPidKlyuchRoute
  '/poslugy/santehnika-elektryka': typeof PoslugySantehnikaElektrykaRoute
  '/poslugy/steli': typeof PoslugySteliRoute
  '/poslugy/zagalnobudivelni-roboty': typeof PoslugyZagalnobudivelniRobotyRoute
  '/en/': typeof EnIndexRoute
  '/poslugy/': typeof PoslugyIndexRoute
  '/en/poslugy/demontazh': typeof EnPoslugyDemontazhRoute
  '/en/poslugy/gipsokarton': typeof EnPoslugyGipsokartonRoute
  '/en/poslugy/ozdoblennya': typeof EnPoslugyOzdoblennyaRoute
  '/en/poslugy/remont-pid-klyuch': typeof EnPoslugyRemontPidKlyuchRoute
  '/en/poslugy/santehnika-elektryka': typeof EnPoslugySantehnikaElektrykaRoute
  '/en/poslugy/steli': typeof EnPoslugySteliRoute
  '/en/poslugy/zagalnobudivelni-roboty': typeof EnPoslugyZagalnobudivelniRobotyRoute
  '/en/poslugy/': typeof EnPoslugyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakty'
    | '/portfolio'
    | '/pro-kompaniyu'
    | '/pryvatnist'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/en/kontakty'
    | '/en/portfolio'
    | '/en/pro-kompaniyu'
    | '/en/pryvatnist'
    | '/poslugy/demontazh'
    | '/poslugy/gipsokarton'
    | '/poslugy/ozdoblennya'
    | '/poslugy/remont-pid-klyuch'
    | '/poslugy/santehnika-elektryka'
    | '/poslugy/steli'
    | '/poslugy/zagalnobudivelni-roboty'
    | '/en/'
    | '/poslugy/'
    | '/en/poslugy/demontazh'
    | '/en/poslugy/gipsokarton'
    | '/en/poslugy/ozdoblennya'
    | '/en/poslugy/remont-pid-klyuch'
    | '/en/poslugy/santehnika-elektryka'
    | '/en/poslugy/steli'
    | '/en/poslugy/zagalnobudivelni-roboty'
    | '/en/poslugy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakty'
    | '/portfolio'
    | '/pro-kompaniyu'
    | '/pryvatnist'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/en/kontakty'
    | '/en/portfolio'
    | '/en/pro-kompaniyu'
    | '/en/pryvatnist'
    | '/poslugy/demontazh'
    | '/poslugy/gipsokarton'
    | '/poslugy/ozdoblennya'
    | '/poslugy/remont-pid-klyuch'
    | '/poslugy/santehnika-elektryka'
    | '/poslugy/steli'
    | '/poslugy/zagalnobudivelni-roboty'
    | '/en'
    | '/poslugy'
    | '/en/poslugy/demontazh'
    | '/en/poslugy/gipsokarton'
    | '/en/poslugy/ozdoblennya'
    | '/en/poslugy/remont-pid-klyuch'
    | '/en/poslugy/santehnika-elektryka'
    | '/en/poslugy/steli'
    | '/en/poslugy/zagalnobudivelni-roboty'
    | '/en/poslugy'
  id:
    | '__root__'
    | '/'
    | '/kontakty'
    | '/portfolio'
    | '/pro-kompaniyu'
    | '/pryvatnist'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/en/kontakty'
    | '/en/portfolio'
    | '/en/pro-kompaniyu'
    | '/en/pryvatnist'
    | '/poslugy/demontazh'
    | '/poslugy/gipsokarton'
    | '/poslugy/ozdoblennya'
    | '/poslugy/remont-pid-klyuch'
    | '/poslugy/santehnika-elektryka'
    | '/poslugy/steli'
    | '/poslugy/zagalnobudivelni-roboty'
    | '/en/'
    | '/poslugy/'
    | '/en/poslugy/demontazh'
    | '/en/poslugy/gipsokarton'
    | '/en/poslugy/ozdoblennya'
    | '/en/poslugy/remont-pid-klyuch'
    | '/en/poslugy/santehnika-elektryka'
    | '/en/poslugy/steli'
    | '/en/poslugy/zagalnobudivelni-roboty'
    | '/en/poslugy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktyRoute: typeof KontaktyRoute
  PortfolioRoute: typeof PortfolioRoute
  ProKompaniyuRoute: typeof ProKompaniyuRoute
  PryvatnistRoute: typeof PryvatnistRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EnKontaktyRoute: typeof EnKontaktyRoute
  EnPortfolioRoute: typeof EnPortfolioRoute
  EnProKompaniyuRoute: typeof EnProKompaniyuRoute
  EnPryvatnistRoute: typeof EnPryvatnistRoute
  PoslugyDemontazhRoute: typeof PoslugyDemontazhRoute
  PoslugyGipsokartonRoute: typeof PoslugyGipsokartonRoute
  PoslugyOzdoblennyaRoute: typeof PoslugyOzdoblennyaRoute
  PoslugyRemontPidKlyuchRoute: typeof PoslugyRemontPidKlyuchRoute
  PoslugySantehnikaElektrykaRoute: typeof PoslugySantehnikaElektrykaRoute
  PoslugySteliRoute: typeof PoslugySteliRoute
  PoslugyZagalnobudivelniRobotyRoute: typeof PoslugyZagalnobudivelniRobotyRoute
  EnIndexRoute: typeof EnIndexRoute
  PoslugyIndexRoute: typeof PoslugyIndexRoute
  EnPoslugyDemontazhRoute: typeof EnPoslugyDemontazhRoute
  EnPoslugyGipsokartonRoute: typeof EnPoslugyGipsokartonRoute
  EnPoslugyOzdoblennyaRoute: typeof EnPoslugyOzdoblennyaRoute
  EnPoslugyRemontPidKlyuchRoute: typeof EnPoslugyRemontPidKlyuchRoute
  EnPoslugySantehnikaElektrykaRoute: typeof EnPoslugySantehnikaElektrykaRoute
  EnPoslugySteliRoute: typeof EnPoslugySteliRoute
  EnPoslugyZagalnobudivelniRobotyRoute: typeof EnPoslugyZagalnobudivelniRobotyRoute
  EnPoslugyIndexRoute: typeof EnPoslugyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pryvatnist': {
      id: '/pryvatnist'
      path: '/pryvatnist'
      fullPath: '/pryvatnist'
      preLoaderRoute: typeof PryvatnistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-kompaniyu': {
      id: '/pro-kompaniyu'
      path: '/pro-kompaniyu'
      fullPath: '/pro-kompaniyu'
      preLoaderRoute: typeof ProKompaniyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/': {
      id: '/poslugy/'
      path: '/poslugy'
      fullPath: '/poslugy/'
      preLoaderRoute: typeof PoslugyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/zagalnobudivelni-roboty': {
      id: '/poslugy/zagalnobudivelni-roboty'
      path: '/poslugy/zagalnobudivelni-roboty'
      fullPath: '/poslugy/zagalnobudivelni-roboty'
      preLoaderRoute: typeof PoslugyZagalnobudivelniRobotyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/steli': {
      id: '/poslugy/steli'
      path: '/poslugy/steli'
      fullPath: '/poslugy/steli'
      preLoaderRoute: typeof PoslugySteliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/santehnika-elektryka': {
      id: '/poslugy/santehnika-elektryka'
      path: '/poslugy/santehnika-elektryka'
      fullPath: '/poslugy/santehnika-elektryka'
      preLoaderRoute: typeof PoslugySantehnikaElektrykaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/remont-pid-klyuch': {
      id: '/poslugy/remont-pid-klyuch'
      path: '/poslugy/remont-pid-klyuch'
      fullPath: '/poslugy/remont-pid-klyuch'
      preLoaderRoute: typeof PoslugyRemontPidKlyuchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/ozdoblennya': {
      id: '/poslugy/ozdoblennya'
      path: '/poslugy/ozdoblennya'
      fullPath: '/poslugy/ozdoblennya'
      preLoaderRoute: typeof PoslugyOzdoblennyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/gipsokarton': {
      id: '/poslugy/gipsokarton'
      path: '/poslugy/gipsokarton'
      fullPath: '/poslugy/gipsokarton'
      preLoaderRoute: typeof PoslugyGipsokartonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslugy/demontazh': {
      id: '/poslugy/demontazh'
      path: '/poslugy/demontazh'
      fullPath: '/poslugy/demontazh'
      preLoaderRoute: typeof PoslugyDemontazhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pryvatnist': {
      id: '/en/pryvatnist'
      path: '/en/pryvatnist'
      fullPath: '/en/pryvatnist'
      preLoaderRoute: typeof EnPryvatnistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pro-kompaniyu': {
      id: '/en/pro-kompaniyu'
      path: '/en/pro-kompaniyu'
      fullPath: '/en/pro-kompaniyu'
      preLoaderRoute: typeof EnProKompaniyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/portfolio': {
      id: '/en/portfolio'
      path: '/en/portfolio'
      fullPath: '/en/portfolio'
      preLoaderRoute: typeof EnPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/kontakty': {
      id: '/en/kontakty'
      path: '/en/kontakty'
      fullPath: '/en/kontakty'
      preLoaderRoute: typeof EnKontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/poslugy/': {
      id: '/en/poslugy/'
      path: '/en/poslugy'
      fullPath: '/en/poslugy/'
      preLoaderRoute: typeof EnPoslugyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/poslugy/zagalnobudivelni-roboty': {
      id: '/en/poslugy/zagalnobudivelni-roboty'
      path: '/en/poslugy/zagalnobudivelni-roboty'
      fullPath: '/en/poslugy/zagalnobudivelni-roboty'
      preLoaderRoute: typeof EnPoslugyZagalnobudivelniRobotyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/poslugy/steli': {
      id: '/en/poslugy/steli'
      path: '/en/poslugy/steli'
      fullPath: '/en/poslugy/steli'
      preLoaderRoute: typeof EnPoslugySteliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/poslugy/santehnika-elektryka': {
      id: '/en/poslugy/santehnika-elektryka'
      path: '/en/poslugy/santehnika-elektryka'
      fullPath: '/en/poslugy/santehnika-elektryka'
      preLoaderRoute: typeof EnPoslugySantehnikaElektrykaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/poslugy/remont-pid-klyuch': {
      id: '/en/poslugy/remont-pid-klyuch'
      path: '/en/poslugy/remont-pid-klyuch'
      fullPath: '/en/poslugy/remont-pid-klyuch'
      preLoaderRoute: typeof EnPoslugyRemontPidKlyuchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/poslugy/ozdoblennya': {
      id: '/en/poslugy/ozdoblennya'
      path: '/en/poslugy/ozdoblennya'
      fullPath: '/en/poslugy/ozdoblennya'
      preLoaderRoute: typeof EnPoslugyOzdoblennyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/poslugy/gipsokarton': {
      id: '/en/poslugy/gipsokarton'
      path: '/en/poslugy/gipsokarton'
      fullPath: '/en/poslugy/gipsokarton'
      preLoaderRoute: typeof EnPoslugyGipsokartonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/poslugy/demontazh': {
      id: '/en/poslugy/demontazh'
      path: '/en/poslugy/demontazh'
      fullPath: '/en/poslugy/demontazh'
      preLoaderRoute: typeof EnPoslugyDemontazhRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktyRoute: KontaktyRoute,
  PortfolioRoute: PortfolioRoute,
  ProKompaniyuRoute: ProKompaniyuRoute,
  PryvatnistRoute: PryvatnistRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EnKontaktyRoute: EnKontaktyRoute,
  EnPortfolioRoute: EnPortfolioRoute,
  EnProKompaniyuRoute: EnProKompaniyuRoute,
  EnPryvatnistRoute: EnPryvatnistRoute,
  PoslugyDemontazhRoute: PoslugyDemontazhRoute,
  PoslugyGipsokartonRoute: PoslugyGipsokartonRoute,
  PoslugyOzdoblennyaRoute: PoslugyOzdoblennyaRoute,
  PoslugyRemontPidKlyuchRoute: PoslugyRemontPidKlyuchRoute,
  PoslugySantehnikaElektrykaRoute: PoslugySantehnikaElektrykaRoute,
  PoslugySteliRoute: PoslugySteliRoute,
  PoslugyZagalnobudivelniRobotyRoute: PoslugyZagalnobudivelniRobotyRoute,
  EnIndexRoute: EnIndexRoute,
  PoslugyIndexRoute: PoslugyIndexRoute,
  EnPoslugyDemontazhRoute: EnPoslugyDemontazhRoute,
  EnPoslugyGipsokartonRoute: EnPoslugyGipsokartonRoute,
  EnPoslugyOzdoblennyaRoute: EnPoslugyOzdoblennyaRoute,
  EnPoslugyRemontPidKlyuchRoute: EnPoslugyRemontPidKlyuchRoute,
  EnPoslugySantehnikaElektrykaRoute: EnPoslugySantehnikaElektrykaRoute,
  EnPoslugySteliRoute: EnPoslugySteliRoute,
  EnPoslugyZagalnobudivelniRobotyRoute: EnPoslugyZagalnobudivelniRobotyRoute,
  EnPoslugyIndexRoute: EnPoslugyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
