// All user-facing interface copy, per language. `uk` is the source of truth for structure:
// `en` must provide every key (checked by the type below).
export type Lang = "uk" | "en";

export const uk = {
  common: {
    skip: "Перейти до вмісту",
    brandHome: "БК Слава, головна",
    brandSub: "БУДУЄМО З 2006 РОКУ",
    logoAlt: "Логотип ТОВ БК Слава",
    consult: "Записатися на консультацію",
    consultShort: "Консультація",
    company: "ТОВ БК Слава",
    home: "Головна",
    services: "Послуги",
    portfolio: "Наші роботи",
    about: "Про компанію",
    contacts: "Контакти",
    privacy: "Приватність",
    phone: "Телефон",
    langLabel: "Мова сайту",
    langUk: "Українська",
    langEn: "English",
  },
  nav: {
    main: "Основна навігація",
    mobile: "Мобільна навігація",
    open: "Відкрити меню",
    close: "Закрити меню",
    title: "БК Слава",
    description: "Будівельні та ремонтні роботи з 2006 року.",
  },
  footer: {
    tagline: ["Продумані рішення.", "Акуратне виконання.", "Київ та Київська область."],
    since: "Працюємо з 2006 року",
  },
  form: {
    close: "Закрити форму",
    topline: "БК СЛАВА / КОНСУЛЬТАЦІЯ",
    title: ["Ваш простір.", "Наш наступний крок."],
    description: "Розкажіть про об’єкт. Підготуємо звернення, щоб вам було зручно обговорити деталі.",
    doneTitle: "Звернення підготовлено",
    storedYes:
      "Дані збережено лише у цьому браузері на час сесії. Автоматичне надсилання ще не підключене.",
    storedNo: "Дані доступні лише у відкритій формі. Автоматичне надсилання ще не підключене.",
    sendMail: "Надіслати через пошту",
    back: "Повернутися до форми",
    name: "Ваше ім’я *",
    namePlaceholder: "Як до вас звертатися",
    phone: "Телефон *",
    phonePlaceholder: "+380 __ ___ __ __",
    place: "Де знаходиться об’єкт?",
    placePlaceholder: "Київ або населений пункт області",
    what: "Що плануєте зробити?",
    choose: "Обрати напрямок",
    message: "Кілька слів про завдання",
    messagePlaceholder: "Тип приміщення, стан і бажаний результат",
    consent: "Погоджуюсь на обробку даних згідно з",
    privacyLink: "політикою приватності",
    submit: "Підготувати звернення",
    direct: "Або зв’яжіться напряму:",
    errName: "Вкажіть, будь ласка, ваше ім’я.",
    errPhone: "Вкажіть український номер: +380 та 9 цифр або 0 та 9 цифр.",
    errConsent: "Підтвердьте згоду на обробку контактних даних.",
    mailSubject: "Консультація БК Слава",
    mailName: "Ім’я",
    mailPhone: "Телефон",
    mailPlace: "Об’єкт",
    mailService: "Послуга",
  },
  intro: {
    title: "Вступне відео БК Слава",
    caption: "ТОВ БК СЛАВА",
    tagline: "АРХІТЕКТУРА ТОЧНОСТІ / З 2006 РОКУ",
    skip: "Перейти на сайт",
  },
  home: {
    heroAlt: "Світла вітальня з природними матеріалами та зеленою кухнею",
    kicker: "БУДІВЕЛЬНА КОМПАНІЯ • КИЇВ ТА ОБЛАСТЬ",
    title: ["Простір, у якому", "хочеться жити."],
    lead: "Ремонт і будівельні роботи з увагою до кожної деталі.",
    caption: "ЖИТЛОВІ ТА КОМЕРЦІЙНІ ПРОСТОРИ",
    yearEyebrow: "ТОВ БК СЛАВА / НАША ІСТОРІЯ",
    yearBaseline: "ВІДТОДІ БУДУЄМО ВАШ ПРОСТІР",
    yearTitle: "20 років досвіду, що стає основою.",
    yearText:
      "ТОВ БК Слава працює з 2006 року. Виконуємо ремонтні та будівельні роботи у Києві й Київській області, поєднуючи практичні рішення з акуратним виконанням.",
    yearLink: "Познайомитися з компанією",
  },
  carousel: {
    label: "Наші роботи",
    eyebrow: "НАШІ РОБОТИ / ПРОСТІР. МАТЕРІАЛИ. ДЕТАЛІ.",
    title: "Наші роботи",
    prev: "Попередня робота",
    next: "Наступна робота",
    group: "Карусель робіт",
    foot: "Добірка напрямків наших робіт. Зображення — архітектурні візуалізації.",
    all: "Усі наші роботи",
  },
  directory: {
    titleFull: "Один процес. Різні завдання.",
    title: "Роботи, що формують простір.",
    text: "Повний ремонт або окремий етап. Обирайте напрямок, який потрібен вашому об’єкту.",
    previewLabel: "НАПРЯМОК РОБІТ",
    more: "Докладніше про послугу",
  },
  reviews: {
    eyebrow: "ДОСВІД СПІВПРАЦІ",
    title: "Відгуки",
    note: "Підготовлені тексти для погодження компанією; відгуки ще не підтверджені.",
    all: "Усі відгуки",
  },
  process: {
    eyebrow: "ПОСЛІДОВНІСТЬ, ЯКА ДАЄ РЕЗУЛЬТАТ",
    title: ["Від задуму ", "до останньої деталі."],
  },
  band: {
    kicker: "Є ІДЕЯ ДЛЯ ВАШОГО ОБ’ЄКТА?",
    title: ["Почнемо з", "вашого простору."],
  },
  breadcrumb: "Шлях сторінки",
  servicesPage: {
    title: ["Будуємо основу.", "Завершуємо деталі."],
    text: "Сім напрямків для цілісного результату. Працюємо з квартирами, будинками, офісами й комерційними приміщеннями.",
    bannerAlt: "Сучасний житловий простір із натуральними матеріалами",
  },
  servicePage: {
    label: "КИЇВ ТА КИЇВСЬКА ОБЛАСТЬ",
    approach: ["Продуманий підхід.", "Видимий результат."],
    scopeTitle: "Що виконуємо",
    scopeText:
      "Обсяг робіт погоджуємо після знайомства з об’єктом. Тут можна обрати потрібні завдання.",
    resultLabel: "РЕЗУЛЬТАТ, ДО ЯКОГО ПРАЦЮЄМО",
    faqTitle: "Перед початком робіт",
    faq: [
      [
        "Як визначається вартість?",
        "Після обговорення задачі та огляду приміщення. На вартість впливають стан основ, обсяг, матеріали й умови виконання. Погоджуємо склад робіт до початку.",
      ],
      [
        "Чи можна замовити тільки цей напрямок?",
        "Так. Напрямок можна обговорити як окреме завдання або як частину комплексного ремонту.",
      ],
      [
        "Що підготувати для консультації?",
        "Адресу або населений пункт, опис стану приміщення та бажаного результату. План і фотографії допоможуть точніше обговорити завдання.",
      ],
      [
        "У яких населених пунктах працюєте?",
        "Київ та Київська область. Деталі виїзду й організації робіт погоджуємо для вашого об’єкта.",
      ],
    ],
    next: "Наступний напрямок",
  },
  compare: {
    afterAlt: "Візуалізація цього приміщення після ремонту",
    beforeAlt: "Приміщення з чорновими поверхнями до ремонту",
    before: "До",
    after: "Після",
    slider: "Порівняти вигляд до та після ремонту",
    valueText: (v: number) => `${v}% до ремонту, ${100 - v}% після ремонту`,
    hint: "Рухайте розділювач, щоб порівняти. Візуалізація перетворення, створена для ілюстрації можливого результату.",
  },
  portfolioPage: {
    title: "Наші роботи",
    text: "Добірка напрямків наших робіт для житлових і комерційних просторів. Архітектурні візуалізації показують характер матеріалів і можливий результат; вони не є фотографіями виконаних об’єктів компанії.",
    filtersLabel: "Категорії робіт",
    all: "Усі",
    categories: [
      "Житлові простори",
      "Комерційні простори",
      "Оздоблення",
      "Підготовка та монтаж",
    ],
    count: (_n: number) => " робіт у добірці",
    changeTitle: "Побачити зміни.",
    changeText: "Від підготовленої основи до продуманого інтер’єру.",
    closeProject: "Закрити проєкт",
    visualisation: "ВІЗУАЛІЗАЦІЯ",
    discuss: "Обговорити ваш проєкт",
  },
  about: {
    title: ["Міцна основа.", "Від 2006 року."],
    text: "ТОВ БК Слава. Будівельні та ремонтні роботи у Києві й Київській області.",
    logoAlt: "Оригінальний логотип ТОВ БК Слава",
    heading: "Досвід у кожному рішенні.",
    p1: "Компанія працює з 2006 року. Для нас ремонт починається з розуміння об’єкта: його стану, призначення та ваших очікувань.",
    p2: "Поєднуємо окремі роботи в послідовний процес. Від демонтажу й підготовки до конструкцій, інженерії та фінішного оздоблення.",
    p3: "Можна звернутися з комплексним ремонтом або конкретним завданням. Разом визначимо, що потрібно саме вашому приміщенню.",
    since: "З 2006",
    sinceSmall: "КИЇВ ТА ОБЛАСТЬ",
    valuesTitle: ["Увага до того,", "що має значення."],
    values: [
      ["Ясність домовленостей", "Обговорюємо склад робіт і важливі рішення до їх виконання."],
      ["Логіка етапів", "Плануємо процес так, щоб зберігати якість уже виконаного."],
      ["Увага до основи", "Підготовка, монтаж і приховані роботи визначають якість фінішу."],
      ["Акуратні деталі", "Примикання, кути та стики формують цілісний вигляд простору."],
    ],
  },
  contactsPage: {
    title: ["Хороший ремонт", "починається з розмови."],
    text: "Київ та Київська область. Обговоримо ваш об’єкт, потрібні роботи й наступний крок.",
    call: "ЗАТЕЛЕФОНУЙТЕ НАМ",
    write: "АБО НАПИШІТЬ",
    imageAlt: "Архітектурні деталі з металу, скла та мінеральних поверхонь",
    invitation: ["Ваші плани.", "Наша увага."],
    prepTitle: ["Щоб розмова", "була предметною."],
    p1: "Підготуйте короткий опис завдання: тип приміщення, населений пункт, поточний стан і бажаний результат.",
    p2: "Якщо маєте план або фотографії об’єкта, їх можна передати під час спілкування у WhatsApp або Viber.",
    p3: "Терміни, обсяг і вартість визначаємо після знайомства із завданням.",
  },
  privacyPage: {
    title: "Політика приватності",
    contact: "Контакт для питань щодо даних:",
    company: "Компанія: ТОВ БК Слава.",
    sections: [
      [
        "Форма консультації",
        "У цій версії сайту форма готує звернення та зберігає його лише у sessionStorage вашого браузера на час поточної сесії. Дані автоматично не надсилаються компанії. Ви можете самостійно відправити підготовлений текст через свій поштовий застосунок.",
      ],
      [
        "Контактні дані",
        "За вашим бажанням форма містить ім’я, номер телефону, населений пункт, обраний напрямок та опис завдання. Не вказуйте у повідомленні конфіденційні дані, які не потрібні для консультації.",
      ],
      [
        "Зовнішні сервіси",
        "Посилання на WhatsApp, Viber і пошту відкривають відповідні сторонні сервіси. Подальша обробка інформації відбувається згідно з їхніми політиками.",
      ],
      [
        "Локальне зберігання",
        "Сайт також зберігає у поточній сесії позначку перегляду вступного відео. Аналітичні та рекламні трекери не підключені. Закриття сесії браузера видаляє ці локальні дані.",
      ],
      [
        "Ваші звернення",
        "Питання щодо повідомлень, які ви самостійно надіслали компанії, можна адресувати на вказану пошту.",
      ],
    ],
  },
  notFound: {
    title: "Тут ще немає простору.",
    text: "Сторінку не знайдено. Поверніться до головної, щоб продовжити.",
    home: "На головну",
    errorTitle: "Сторінка не завантажилась.",
    errorText: "Спробуйте оновити її або повернутися на головну.",
  },
  meta: {
    homeTitle: "Ремонт та будівництво у Києві",
    homeText:
      "ТОВ БК Слава працює з 2006 року. Ремонт під ключ, демонтаж, гіпсокартон, стелі та оздоблення у Києві й області.",
    servicesText:
      "Ремонт під ключ, демонтаж, гіпсокартон, стелі, оздоблення, сантехніка та електрика. Київ та область.",
    portfolioText: "Архітектурні рішення та візуалізації житлових і комерційних просторів.",
    aboutText: "ТОВ БК Слава працює з 2006 року у Києві та Київській області.",
    contactsText: "Телефон +380 67 609 00 75. WhatsApp, Viber, email. Запис на консультацію.",
    privacyText: "Обробка контактних даних у формі консультації БК Слава.",
    suffix: "ТОВ БК Слава",
    locale: "uk_UA",
  },
};

export type UI = typeof uk;

export const en: UI = {
  common: {
    skip: "Skip to content",
    brandHome: "BK Slava, home",
    brandSub: "BUILDING SINCE 2006",
    logoAlt: "BK Slava LLC logo",
    consult: "Book a consultation",
    consultShort: "Consultation",
    company: "BK Slava LLC",
    home: "Home",
    services: "Services",
    portfolio: "Our work",
    about: "About us",
    contacts: "Contact",
    privacy: "Privacy",
    phone: "Phone",
    langLabel: "Site language",
    langUk: "Ukrainian",
    langEn: "English",
  },
  nav: {
    main: "Main navigation",
    mobile: "Mobile navigation",
    open: "Open menu",
    close: "Close menu",
    title: "BK Slava",
    description: "Construction and renovation in Kyiv and Kyiv Region since 2006.",
  },
  footer: {
    tagline: ["Thoughtful solutions.", "Careful execution.", "Kyiv and Kyiv Region."],
    since: "Since 2006",
  },
  form: {
    close: "Close form",
    topline: "BK SLAVA / CONSULTATION",
    title: ["Tell us about", "your project."],
    description:
      "Tell us about your property and the work you need. We’ll prepare a summary you can send by email.",
    doneTitle: "Your enquiry is ready",
    storedYes:
      "Your details are saved in this browser for the current session. The form does not send them automatically.",
    storedNo:
      "Your details are still in this form. The form does not send them automatically.",
    sendMail: "Send by email",
    back: "Back to the form",
    name: "Your name *",
    namePlaceholder: "Enter your name",
    phone: "Phone *",
    phonePlaceholder: "+380 __ ___ __ __",
    place: "Property location",
    placePlaceholder: "Kyiv or a town in Kyiv Region",
    what: "What work do you need?",
    choose: "Choose a service",
    message: "Project details",
    messagePlaceholder: "Type of property, current condition and desired result",
    consent: "I agree to the processing of my contact details as described in the",
    privacyLink: "privacy policy",
    submit: "Prepare enquiry",
    direct: "Or contact us directly:",
    errName: "Please enter your name.",
    errPhone: "Enter a Ukrainian phone number: +380 and 9 digits, or 0 and 9 digits.",
    errConsent: "Please confirm your consent to the processing of your contact details.",
    mailSubject: "BK Slava consultation enquiry",
    mailName: "Name",
    mailPhone: "Phone",
    mailPlace: "Property",
    mailService: "Service",
  },
  intro: {
    title: "BK Slava introduction video",
    caption: "BK SLAVA LLC",
    tagline: "ARCHITECTURE OF PRECISION / SINCE 2006",
    skip: "Enter the site",
  },
  home: {
    heroAlt: "Bright living room with natural materials and a green kitchen",
    kicker: "CONSTRUCTION COMPANY • KYIV AND KYIV REGION",
    title: ["A space you", "want to live in."],
    lead: "Renovation and construction with attention to every detail.",
    caption: "RESIDENTIAL AND COMMERCIAL SPACES",
    yearEyebrow: "BK SLAVA LLC / OUR STORY",
    yearBaseline: "BUILDING SPACES SINCE 2006",
    yearTitle: "20 years of construction experience.",
    yearText:
      "BK Slava LLC has worked in Kyiv and Kyiv Region since 2006. We combine practical solutions with careful workmanship across renovation and construction projects.",
    yearLink: "About the company",
  },
  carousel: {
    label: "Our work",
    eyebrow: "OUR WORK / SPACES. MATERIALS. DETAILS.",
    title: "Our work",
    prev: "Previous project",
    next: "Next project",
    group: "Project carousel",
    foot: "Examples of the work we cover, shown through architectural visualisations.",
    all: "All our work",
  },
  directory: {
    titleFull: "One process. Different tasks.",
    title: "Construction and renovation services.",
    text: "A full renovation or a single stage. Choose the service your property needs.",
    previewLabel: "SERVICE",
    more: "More about this service",
  },
  reviews: {
    eyebrow: "WORKING TOGETHER",
    title: "Reviews",
    note: "Draft review text awaiting company approval. These accounts have not been verified.",
    all: "All reviews",
  },
  process: {
    eyebrow: "HOW WE WORK",
    title: ["From the first discussion ", "to the final detail."],
  },
  band: {
    kicker: "PLANNING A PROJECT?",
    title: ["Let’s start with", "your space."],
  },
  breadcrumb: "Breadcrumb",
  servicesPage: {
    title: ["We build the foundation.", "We finish the details."],
    text: "Seven services covering construction and renovation for apartments, houses, offices and commercial premises.",
    bannerAlt: "Modern residential space with natural materials",
  },
  servicePage: {
    label: "KYIV AND KYIV REGION",
    approach: ["Careful planning.", "Quality workmanship."],
    scopeTitle: "What we do",
    scopeText:
      "We agree on the scope after inspecting the property. These are the tasks we can discuss for your project.",
    resultLabel: "THE EXPECTED RESULT",
    faqTitle: "Before work begins",
    faq: [
      [
        "How is the cost determined?",
        "We discuss the project and inspect the property before estimating the cost. The condition of existing surfaces, the scope of work, materials and site conditions all affect the price. We agree on the scope before work begins.",
      ],
      [
        "Can I order just this service?",
        "Yes. We can discuss it as a separate job or as part of a full renovation.",
      ],
      [
        "What should I prepare for the consultation?",
        "The address or town, a description of the property’s condition and the result you want. A floor plan and photos will help us discuss the work in more detail.",
      ],
      [
        "Which areas do you cover?",
        "Kyiv and Kyiv Region. We discuss site access and logistics for each property.",
      ],
    ],
    next: "Next service",
  },
  compare: {
    afterAlt: "Visualisation of this space after renovation",
    beforeAlt: "Space with rough surfaces before renovation",
    before: "Before",
    after: "After",
    slider: "Compare the view before and after renovation",
    valueText: (v: number) => `${v}% before renovation, ${100 - v}% after renovation`,
    hint: "Move the divider to compare the views. This visualisation illustrates a possible result.",
  },
  portfolioPage: {
    title: "Our work",
    text: "Explore our work across residential and commercial spaces. These architectural visualisations show materials and possible results; they are not photographs of projects completed by the company.",
    filtersLabel: "Work categories",
    all: "All",
    categories: ["Residential spaces", "Commercial spaces", "Interior finishing", "Preparation and installation"],
    count: (n: number) => (n === 1 ? " project shown" : " projects shown"),
    changeTitle: "Before and after.",
    changeText: "From the prepared space to a finished interior.",
    closeProject: "Close project",
    visualisation: "VISUALISATION",
    discuss: "Discuss your project",
  },
  about: {
    title: ["Built on experience.", "Since 2006."],
    text: "BK Slava LLC. Construction and renovation in Kyiv and Kyiv Region.",
    logoAlt: "Original BK Slava LLC logo",
    heading: "Experience that guides the work.",
    p1: "BK Slava LLC has worked since 2006. Every renovation starts with understanding the property, how it will be used and what you expect from the result.",
    p2: "We coordinate each stage, from demolition and preparation through structural work, plumbing and electrical installation, to the final finishes.",
    p3: "Whether you need a full renovation or help with one part of the project, we’ll discuss what the property requires.",
    since: "Since 2006",
    sinceSmall: "KYIV AND KYIV REGION",
    valuesTitle: ["The details that", "matter most."],
    values: [
      ["Clear agreements", "We agree on the scope and key decisions before work begins."],
      ["A clear sequence", "We plan each stage to protect the quality of work already completed."],
      ["Proper preparation", "Surface preparation, installation and concealed work all affect the final finish."],
      ["Careful finishing", "Neat junctions, corners and joints bring the space together."],
    ],
  },
  contactsPage: {
    title: ["A good renovation", "starts with a conversation."],
    text: "Tell us about your property in Kyiv or Kyiv Region. We’ll discuss the work you need and the next step.",
    call: "CALL US",
    write: "OR WRITE TO US",
    imageAlt: "Architectural details in metal, glass and mineral surfaces",
    invitation: ["Tell us what", "you have in mind."],
    prepTitle: ["What to have ready", "when you contact us."],
    p1: "A short description helps: the type of property, its location and condition, and the result you want.",
    p2: "If you have a floor plan or photos, you can share them during a conversation on WhatsApp or Viber.",
    p3: "We discuss the timeline, scope and cost after reviewing the project.",
  },
  privacyPage: {
    title: "Privacy policy",
    contact: "For questions about your data, contact:",
    company: "Company: BK Slava LLC.",
    sections: [
      [
        "Consultation form",
        "The consultation form prepares an enquiry and stores it in your browser’s sessionStorage for the current session. It does not send your details to the company automatically. You can send the prepared message through your email app.",
      ],
      [
        "Contact details",
        "You may enter your name, phone number, town, selected service and a description of the work. Please leave out confidential information that is not needed for the consultation.",
      ],
      [
        "External services",
        "The WhatsApp, Viber and email links open those services. Their own policies govern how they process information you share there.",
      ],
      [
        "Local storage",
        "The site also records in the current session whether you have viewed the introduction video. No analytics or advertising trackers are connected. This local data is removed when the browser session ends.",
      ],
      [
        "Your messages",
        "If you have questions about a message you sent to the company, use the email address above.",
      ],
    ],
  },
  notFound: {
    title: "Page not found.",
    text: "The page you’re looking for is unavailable. Return to the home page to continue.",
    home: "Go to home page",
    errorTitle: "The page failed to load.",
    errorText: "Try refreshing it or going back to the home page.",
  },
  meta: {
    homeTitle: "Renovation and construction in Kyiv",
    homeText:
      "BK Slava LLC has worked in Kyiv and Kyiv Region since 2006. Turnkey renovation, demolition work, drywall construction, suspended ceilings and interior finishing.",
    servicesText:
      "Seven construction and renovation services in Kyiv and Kyiv Region: turnkey renovation, demolition work, drywall construction, suspended ceilings, interior finishing, plumbing and electrical work, and general construction work.",
    portfolioText: "Architectural visualisations of residential and commercial spaces, showing materials and possible results.",
    aboutText: "BK Slava LLC has been working since 2006 in Kyiv and Kyiv Region.",
    contactsText: "Phone +380 67 609 00 75. WhatsApp, Viber, email. Book a consultation.",
    privacyText: "How contact details are handled in the BK Slava consultation form.",
    suffix: "BK Slava LLC",
    locale: "en_US",
  },
};

export const ui: Record<Lang, UI> = { uk, en };
